### ISSUE TITLE
[Bug] Bot doesn't auto duel

### ISSUE THREAD

**Issue by curtiola** [will7200/Yugioh-bot#15]
[yugioh-bot-log.txt](https://github.com/will7200/Yugioh-bot/files/1585132/yugioh-bot-log.txt)
I've copied the log text to notepad & attached it, just in case you can spot something I can't,
I haven't changed any defaults in config or anywhere.

In the 1st block, when it says "Tapping at location (208,700)" it taps the event bar at the bottom,
& then just stops & sits in that menu.

In the 2nd block, where it shows:
2017-12-24 17:09 - DEBUG - bot.provider.Nox - Tapping at location (254,436)
2017-12-24 17:09 - DEBUG - bot.provider.Nox - Tapping at location (150,400)
2017-12-24 17:09 - DEBUG - bot.provider.Nox - Verifying battle
I think it's tapping too fast, the Auto-duel button barely shows up, then it says "Verifying battle",
& then just sits in that Duel/Auto-duel menu.

This could all be my fault, I have no idea, but I followed instructions as closely as I could.

I'd be glad to provide any more information you need, any assistance would be appreciated, thanks!

**Comment by will7200** [comment]
So I have implemented a sleep factor into the bot to account for various hardware running the software since Nox is a emulator. I just have not brought it out to the config file. I will bring it out so the sleep factor to the config file so that the sleep calls can be elongated. 

If you could provide a video that would also help, the log file also is telling me that the that the run through falling, there must be an unhandled exception some where.

**Comment by curtiola** [comment]
There could be something missing, I had to manually pip install Deprecation & PyQt5 as well as add the python directory paths into the System Properties > Environment Variables. No idea why, I checked the option to add it's location to environment when installing.

https://youtu.be/4MLv4r2XGHE

Thanks for the help!
Happy holidays :D

**Comment by curtiola** [comment]
Also I don't know if it's relevant but I have Hyper-V disabled because it recently started causing a BSoD when I run any emulators, that started when I installed Visual Studios 2017.

**Comment by will7200** [comment]
Thanks for pointing that out. I have updated the dependencies for this projects as well as giving a note about the BSoD error. I complete forgot about that error since it occurred to me a log time ago. 

I implemented the sleep factor in the config file, so you can change that. With one being the base lowering will increase sleeps between calls and increasing will prolong calls to the sleeps. So give that a try and see if that fixes it.

I can't seem to reproduce the error that you keep experiencing, so I added some logging to the problem area that you are experiencing. Also would you give me you python version that you are using.
I tested this in 3.5.4 and in 3.6.3.

**Comment by curtiola** [comment]
I've been using 3.6.4, I'll give it a shot with 3.6.3 & let you know how that goes, as well as provide those logs afterwards.

**Comment by curtiola** [comment]
I'm getting the same problem as before with 3.6.3 & changing the sleep factor in config doesn't seem to help sadly, it doesn't seem to actually press in the auto duel button location, it taps the duelist, then to skip dialogue, & then tries to verify the battle but doesn't tap.
Here is an events log: 
[events.log](https://github.com/will7200/Yugioh-bot/files/1589191/events.log)

This was a weird one:
[events1.txt](https://github.com/will7200/Yugioh-bot/files/1589180/events1.txt)
It went into the gate and back, then went into missions and back twice, clicking in the middle of nowhere in between, & then found one of those yellow item things & said it "completed auto play through" without hitting the ok button.

**Comment by will7200** [comment]
Yes the algorithm for npc detection is not the best as it tries to detect circles on the screen so occasionally it will tap on things that are not relevant at all as well as the world rewards. I made it this way since I have no real experience using memory scanners to find things.

So this looks like an issue with the OCR, as both the duel button and ok button depend on it as it check the word before clicking it. You log also doesn't go past the check point of which auto-duel version found(one with auto-duel button and one without), that I implemented in e0f2c5f038d5083766d2f0a56d5d6f660a713b98. The thing that bother me though is that the exception is not printing since the whole auto play through is in catch blocks.

Do you have tess installed the bin directory?
Run this command from the root directory of this repo:
````bash
bin\\tess\\tesseract.exe --tessdata-dir bin\\tess\\tessdata tmp\\ocr.png tmp\\ocr -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ -psm 7> nul 2>&1
````
And give me its output. There should be an old tmp\\ocr.png from the previous runs if not just run it again.

**Comment by curtiola** [comment]
I think I do, all i did was extract it & copy the files into bin\tess
![image](https://user-images.githubusercontent.com/16383836/34387081-5eb7af7c-eae9-11e7-8b2d-396348f94e46.png)
& when I run that command here is the output:
C:\Users\Chronic\Yugioh-bot>bin\tess\tesseract.exe --tessdata-dir bin\tess\tessdata tmp\ocr.png tmp\ocr -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ -psm 7> nul 2>&1
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
ERROR: Can not open input file tmp\ocr.png
Error during processing.

**Comment by will7200** [comment]
Do you have a tmp folder in the root director?

**Comment by curtiola** [comment]
No tmp folder

**Comment by will7200** [comment]
Ok make one in the root directory and try the bot again. I will put that in the program to make and check that it exists.

**Comment by curtiola** [comment]
A bit of progress, created the tmp folder, here's the log from afterwards:
[events.log](https://github.com/will7200/Yugioh-bot/files/1589822/events.log)
& that commands results:
C:\Users\Chronic\Yugioh-bot>bin\tess\tesseract.exe --tessdata-dir bin\tess\tessdata tmp\ocr.png tmp\ocr -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ -psm 7> nul 2>&1
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica

It still hasn't started the duel, but this time it said:
2017-12-27 13:27 - INFO - bot.provider.Nox - Verifying battle
2017-12-27 13:27 - DEBUG - bot.provider.Nox - Duel-Buttons Version 2
2017-12-27 13:27 - INFO - bot.provider.Nox - NPC Battle Mode,Points: (170,482) at location: (2), message: Starting Battle

**Comment by will7200** [comment]
I fixed the battle tuple extraction and the uncaught exception in the Nox scanner in acd5732ffceb1565bf6b0269f245ff447270e22c.

**Comment by curtiola** [comment]
Have I done something wrong?
[oops.txt](https://github.com/will7200/Yugioh-bot/files/1589925/oops.txt)
I haven't seen this before
