### ISSUE TITLE
you can make Steam version ?

### ISSUE THREAD

**Issue by asdasd888** [will7200/Yugioh-bot#16]
you can make Duel links bot PC Steam version ?
http://store.steampowered.com/app/601510/YuGiOh_Duel_Links/

**Comment by curtiola** [comment]
you can use the same account on Nox & the steam version, just use the Konami ID data transfer

**Comment by asdasd888** [comment]
yes i know but android version 2.2.0 cannot use GG

**Comment by curtiola** [comment]
Why use 2.2? Use the latest version of Nox, 6.0.1.1 default is android 5.1, https://www.bignox.com/

**Comment by asdasd888** [comment]
i mean duel link 2.2.0 android version

**Comment by curtiola** [comment]
Ohhh ok sorry lol you can use the modded APK if you trust it, you can get v5 with cards visible & 8k points instant win version [here](https://drive.google.com/file/d/1YKB91YNLNEUXEakMcyqeODWVbTnu5RhX/view)

**Comment by will7200** [comment]
I am working on it. One thing about the Steam version is that that user will see application movement between whatever you are doing and the bot, since the bot has to take focus to be able to click anywhere. It also has to be on the screen for any clicking to occur, unlike the nox version where it can be minimized.

**Comment by will7200** [comment]
Resolved in #24
