### ISSUE TITLE
What does '(or use conda if using)' mean in setup instructions?

### ISSUE THREAD

**Issue by trwnh** [will7200/Yugioh-bot#46]
This is nonsensical and unintelligible. For users of Python, which do we install - requirements.txt, or install-requirements.txt?

**Comment by curtiola** [comment]
Conda is used if you have multiple installations of different Python versions.
& to your 2nd question, both requirements.txt & install_requirements.txt, in the order written in the instructions.

**Comment by NaniteFactory** [comment]
It means that you can use `conda` instead of `pip` when you install the requirements, of your own choice
(`conda` is a package manager similar to `pip` and provided by Anaconda, the python distribution)
So if your python environment is not managed by Anaconda you would want to use pip and install the list of items in both requirements.txt and install_requirements.txt.

**Comment by trwnh** [comment]
Ah, then perhaps it should instead say '(or use conda if using anaconda)', or better yet, write out the full command in a separate code-block for anaconda users. It is very confusing and bad grammar the way it currently is.

**Comment by will7200** [comment]
I agree it is nonsensical, I don't have to tell anaconda users to use conda. I will remove it.
